/********************************************************************
 *
 *      File:   fan_reg.c
 *      Name:   Sudharshan Kadari
 *
 *      Description:
 *       Fan Controller. 
 *
 *
 * Copyright (c) 1985-2009 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *
 *********************************************************************/

#include <stdio.h>
#include "diag_reg.h"
#include "adt7476.h"

reg_desc_t fan_reg_desc[] =
{
RCFG(FAN_REG_CFG6)
RCFG(FAN_REG_CFG7)
RCFG(FAN_REG_2P5V_MEASURE)
RCFG(FAN_REG_VCCP_READ)
RCFG(FAN_REG_VCC_READ)
RCFG(FAN_REG_5V_MEASURE)
RCFG(FAN_REG_12V_MEASURE)
RCFG(FAN_REG_RMT1_TEMP)
RCFG(FAN_REG_LCL_TEMP)
RCFG(FAN_REG_RMT2_TEMP)
RCFG(FAN_REG_TACH1_LOW)
RCFG(FAN_REG_TACH1_HIGH)
RCFG(FAN_REG_TACH2_LOW)
RCFG(FAN_REG_TACH2_HIGH)
RCFG(FAN_REG_TACH3_LOW)
RCFG(FAN_REG_TACH3_HIGH)
RCFG(FAN_REG_TACH4_LOW)
RCFG(FAN_REG_TACH4_HIGH)
RCFG(FAN_REG_PWM1)
RCFG(FAN_REG_PWM2)
RCFG(FAN_REG_PWM3)
RCFG(FAN_REG_PWM1_MAX_DUTY_CYCLE)
RCFG(FAN_REG_PWM2_MAX_DUTY_CYCLE)
RCFG(FAN_REG_PWM3_MAX_DUTY_CYCLE)
RCFG(FAN_REG_DEV_ID_REG)
RCFG(FAN_REG_CMPY_ID_REG)
RCFG(FAN_REG_REV_ID_REG)
RCFG(FAN_REG_CFG1)
RCFG(FAN_REG_IRQ_STAT1)
RCFG(FAN_REG_IRQ_STAT2)
RCFG(FAN_REG_VID_GPIO)
RCFG(FAN_REG_2P5V_LOW_LIMIT)
RCFG(FAN_REG_2P5V_HI_LIMIT)
RCFG(FAN_REG_VCCP_LOW_LIMIT)
RCFG(FAN_REG_VCCP_HI_LIMIT)
RCFG(FAN_REG_VCC_LOW_LIMIT)
RCFG(FAN_REG_VCC_HI_LIMIT)
RCFG(FAN_REG_5V_LOW_LIMIT)
RCFG(FAN_REG_5V_HI_LIMIT)
RCFG(FAN_REG_12V_LOW_LIMIT)
RCFG(FAN_REG_12V_HI_LIMIT)
RCFG(FAN_REG_RMT1_LOW_LIMIT)
RCFG(FAN_REG_RMT1_HI_LIMIT)
RCFG(FAN_REG_LCL_LOW_LIMIT)
RCFG(FAN_REG_LCL_HI_LIMIT)
RCFG(FAN_REG_RMT2_LOW_LIMIT)
RCFG(FAN_REG_RMT2_HI_LIMIT)
RCFG(FAN_REG_TACH1_MIN_LOW)
RCFG(FAN_REG_TACH1_MIN_HIGH)
RCFG(FAN_REG_TACH2_MIN_LOW)
RCFG(FAN_REG_TACH2_MIN_HIGH)
RCFG(FAN_REG_TACH3_MIN_LOW)
RCFG(FAN_REG_TACH3_MIN_HIGH)
RCFG(FAN_REG_TACH4_MIN_LOW)
RCFG(FAN_REG_TACH4_MIN_HIGH)
RCFG(FAN_REG_PWM1_CFG)
RCFG(FAN_REG_PWM2_CFG)
RCFG(FAN_REG_PWM3_CFG)
RCFG(FAN_REG_RMT1_PWM1_HZ)
RCFG(FAN_REG_RMT1_PWM2_HZ)
RCFG(FAN_REG_RMT1_PWM3_HZ)
RCFG(FAN_REG_ENHANCED_ACOUSTICS1)
RCFG(FAN_REG_ENHANCED_ACOUSTICS2)
RCFG(FAN_REG_PWM1_MIN_DUTY_CYCLE)
RCFG(FAN_REG_PWM2_MIN_DUTY_CYCLE)
RCFG(FAN_REG_PWM3_MIN_DUTY_CYCLE)
RCFG(FAN_REG_RMT1_TEMP_MIN)
RCFG(FAN_REG_LCL_TEMP_MIN)
RCFG(FAN_REG_RMT2_TEMP_MIN)
RCFG(FAN_REG_RMT1_TEMP_LIMIT)
RCFG(FAN_REG_LCL_TEMP_LIMIT)
RCFG(FAN_REG_RMT2_TEMP_LIMIT)
RCFG(FAN_REG_RMT1_TEMP_HYST)
RCFG(FAN_REG_RMT2_TEMP_HYST)
RCFG(FAN_REG_XNOR_TREE_TEST_EN)
RCFG(FAN_REG_RMT1_TEMP_OFFSET)
RCFG(FAN_REG_LCL_TEMP_OFFSET)
RCFG(FAN_REG_RMT2_TEMP_OFFSET)
RCFG(FAN_REG_CFG2)
RCFG(FAN_REG_IRQ_MASK1)
RCFG(FAN_REG_IRQ_MASK2)
RCFG(FAN_REG_EXT_RES1)
RCFG(FAN_REG_EXT_RES2)
RCFG(FAN_REG_CFG3)
RCFG(FAN_REG_TIMER_STAT)
RCFG(FAN_REG_TIMER_LIMIT)
RCFG(FAN_REG_TACH_PULSES_PER_REV)
RCFG(FAN_REG_CFG5)
RCFG(FAN_REG_CFG4)
RCFG(FAN_REG_TEST1)
RCFG(FAN_REG_TEST2)
{ TYP_NONE, "", 0, 0, "", "", 0, 0, ""}
};
