/********************************************************************
 *
 *      File:   ucd92xx_reg.c
 *      Name:   Sudharshan Kadari
 *
 *      Description:
 *       Digital PWM System Controller register description
 *
 *
 * Copyright (c) 1985-2009 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *
 *********************************************************************/

#include <stdio.h>
#include "diag_reg.h"
#include "ucd92xx.h"

reg_desc_t ucd92xx_reg_desc[] =
{
RCFG(PMBUS_PAGE)
RCFG(PMBUS_OPERATION)
RCFG(PMBUS_ON_OFF_CONFIG)
RCFG(PMBUS_CLEAR_FAULTS)
RCFG(PMBUS_PHASE)

RCFG(PMBUS_STORE_DEFAULT_ALL)
RCFG(PMBUS_RESTORE_DEFAULT_ALL)
RCFG(PMBUS_CAPABILITY)

RCFG(PMBUS_VOUT_MODE)
RCFG(PMBUS_VOUT_COMMAND)
RCFG(PMBUS_VOUT_CAL_OFFSET)
RCFG(PMBUS_VOUT_MAX)
RCFG(PMBUS_VOUT_MARGIN_HI)
RCFG(PMBUS_VOUT_MARGIN_LO)
RCFG(PMBUS_VOUT_TRANSITION_RATE)
RCFG(PMBUS_VOUT_SCALE_LOOP)
RCFG(PMBUS_VOUT_SCALE_MONITOR)

RCFG(PMBUS_MAX_DUTY)
RCFG(PMBUS_FREQUENCY_SWITCH)
RCFG(PMBUS_VIN_ON)
RCFG(PMBUS_VIN_OFF)
RCFG(PMBUS_IOUT_CAL_GAIN)
RCFG(PMBUS_IOUT_CAL_OFFSET)
RCFG(PMBUS_FAN_CONFIG_1_2)
BFLD(PMBUS_FAN_CONFIG_1_2, FAN1_INSTALLED)
BFLD(PMBUS_FAN_CONFIG_1_2, FAN1_RPM)
RFLD(PMBUS_FAN_CONFIG_1_2, FAN1_PULSE_PER_REV)

RCFG(PMBUS_FAN_COMMAND_1)

RCFG(PMBUS_VOUT_OV_FAULT_LIMIT)
RCFG(PMBUS_VOUT_OV_FAULT_RESPONSE)
RCFG(PMBUS_VOUT_OV_WARN_LIMIT)
RCFG(PMBUS_VOUT_UV_WARN_LIMIT)
RCFG(PMBUS_VOUT_UV_FAULT_LIMIT)
RCFG(PMBUS_VOUT_UV_FAULT_RESPONSE)
RCFG(PMBUS_VOUT_OC_FAULT_LIMIT)
RCFG(PMBUS_VOUT_OC_FAULT_RESPONSE)
RCFG(PMBUS_VOUT_OC_LV_FAULT_LIMIT)
RCFG(PMBUS_VOUT_OC_LV_FAULT_RESPONSE)
RCFG(PMBUS_IOUT_OC_WARN_LIMIT)
RCFG(PMBUS_IOUT_UC_FAULT_LIMIT)
RCFG(PMBUS_IOUT_UC_FAULT_RESPONSE)
RCFG(PMBUS_VOUT_OT_FAULT_LIMIT)

RCFG(PMBUS_VOUT_OT_FAULT_RESPONSE)
RCFG(PMBUS_VOUT_OT_WARN_LIMIT)
RCFG(PMBUS_VIN_OV_FAULT_LIMIT)
RCFG(PMBUS_VIN_OV_FAULT_RESPONSE)
RCFG(PMBUS_VIN_OV_WARN_LIMIT)
RCFG(PMBUS_VIN_UV_WARN_LIMIT)
RCFG(PMBUS_VIN_UV_FAULT_LIMIT)
RCFG(PMBUS_VIN_UV_FAULT_RESPONSE)
RCFG(PMBUS_POWER_GOOD_ON)
RCFG(PMBUS_POWER_GOOD_OFF)

RCFG(PMBUS_TON_DELAY)
RCFG(PMBUS_TON_RISE)
RCFG(PMBUS_TON_MAX_FAULT_LIMIT)
RCFG(PMBUS_TON_MAX_FAULT_RESPONSE)
RCFG(PMBUS_TOFF_DELAY)
RCFG(PMBUS_TOFF_FALL)
RCFG(PMBUS_TOFF_MAX_WARN_LIMIT)

RCFG(PMBUS_STATUS_BYTE)
RCFG(PMBUS_STATUS_WORD)
RCFG(PMBUS_STATUS_VOUT)
RCFG(PMBUS_STATUS_IOUT)
RCFG(PMBUS_STATUS_INPUT)
RCFG(PMBUS_STATUS_TEMPERATURE)
RCFG(PMBUS_STATUS_CML)
RCFG(PMBUS_STATUS_OTHER)

RCFG(PMBUS_STATUS_MFR_SPECIFIC)
RCFG(PMBUS_STATUS_FAN_1_2)
RCFG(PMBUS_STATUS_FAN_3_4)
RCFG(PMBUS_READ_VIN)
RCFG(PMBUS_READ_IIN)
RCFG(PMBUS_READ_VOUT)
RCFG(PMBUS_READ_IOUT)
RCFG(PMBUS_READ_TEMPERATURE_1)
RCFG(PMBUS_READ_TEMPERATURE_2)

RCFG(PMBUS_READ_FAN_SPEED_1)


RCFG(PMBUS_READ_POUT)
RCFG(PMBUS_READ_PIN)
RCFG(PMBUS_PMBUS_REVISION)
RCFG(PMBUS_MFR_ID)
RCFG(PMBUS_MFR_MODEL)
RCFG(PMBUS_MFR_REVISION)
RCFG(PMBUS_MFR_LOCATION)
RCFG(PMBUS_MFR_DATE	)
RCFG(PMBUS_MFR_SERIAL)


RCFG(PMBUS_SEQ_TIMEOUT)
RCFG(PMBUS_VOUT_CAL_MONITOR)
RCFG(PMBUS_PHASE_INFO)
RCFG(PMBUS_VIN_SCALE_MONITOR)
RCFG(PMBUS_CLA_BLANK)
RCFG(PMBUS_CLA_GAINS)
RCFG(PMBUS_PAGE_ISOLATED)
RCFG(PMBUS_EADC_SAMPLE_TRIGGER)
RCFG(PMBUS_ACTIVATE_CLA_BLANK)
RCFG(PMBUS_ROM_MODE	)
RCFG(PMBUS_USER_RAM_00)
RCFG(PMBUS_SOFT_RESET)
RCFG(PMBUS_IIN_SCALE_MONITOR)
RCFG(PMBUS_THERMAL_COEF)
RCFG(PMBUS_PHASE_ENABLE)
RCFG(PMBUS_DRIVER_MIN_PULSE)
RCFG(PMBUS_MIN_DUTY	)
RCFG(PMBUS_SYNC_IN_OUT)
RCFG(PMBUS_PARM_INFO)
RCFG(PMBUS_PARM_VALUE)
RCFG(PMBUS_TEMPERATURE_CAL_GAIN)
RCFG(PMBUS_TEMPERATURE_CAL_OFFSET)
RCFG(PMBUS_TRACKING_SOURCE)
RCFG(PMBUS_TRACKING_SCALE_MONITOR)
RCFG(PMBUS_FAN_SPEED_FAULT_LIMIT)
RCFG(PMBUS_LOGGED_PEAKS)
RCFG(PMBUS_LOGGED_FAULTS)
RCFG(PMBUS_LIGHT_LOAD_LIMIT_HIGH)
RCFG(PMBUS_DEVICE_ID_0)
RCFG(PMBUS_LIGHT_LOAD_CONFIG)
RCFG(PMBUS_PREBIAS_OFFSET)
RCFG(PMBUS_PREBIAS_GAIN)
RCFG(PMBUS_EXECUTE_FLASH)
RCFG(PMBUS_MFR_SETUP_PASSWORD)
RCFG(PMBUS_DISABLE_SECURITY)
RCFG(PMBUS_GPIO_SEQ_CONFIG)
RCFG(PMBUS_MFR_SECURITY_BIT_MASK)
RCFG(PMBUS_TEMP_BALANCE_IMIN)
RCFG(PMBUS_LIGHT_LOAD_LIMIT_LOW)
RCFG(PMBUS_FAST_OC_FAULT_LIMIT)
RCFG(PMBUS_EADC_TRIM)
RCFG(PMBUS_DEVICE_ID_1)

{ TYP_NONE, "", 0, 0, "", "", 0, 0, ""}
};
