/** 
 * @file adt7476.h
 *
 * @brief
 *  include file for adt7476 device
 */
/*
 * Author: Sudharshan Kadari (skadari) 
 *
 * Copyright (c), Cisco Systems, 1984-2009
 */
#ifndef _FAN_H__
#define _FAN_H__

/* register defines */
#define FAN_REG_CFG6			0x10
#define FAN_REG_CFG7			0x11
#define FAN_REG_2P5V_MEASURE		0x20
#define FAN_REG_VCCP_READ		0x21
#define FAN_REG_VCC_READ		0x22
#define FAN_REG_5V_MEASURE		0x23
#define FAN_REG_12V_MEASURE		0x24
#define FAN_REG_RMT1_TEMP		0x25
#define FAN_REG_LCL_TEMP		0x26
#define FAN_REG_RMT2_TEMP		0x27
#define FAN_REG_TACH1_LOW		0x28
#define FAN_REG_TACH1_HIGH		0x29
#define FAN_REG_TACH2_LOW		0x2A
#define FAN_REG_TACH2_HIGH		0x2B
#define FAN_REG_TACH3_LOW		0x2C
#define FAN_REG_TACH3_HIGH		0x2D
#define FAN_REG_TACH4_LOW		0x2E
#define FAN_REG_TACH4_HIGH		0x2F
#define FAN_REG_PWM1			0x30
#define FAN_REG_PWM2			0x31
#define FAN_REG_PWM3			0x32
#define FAN_REG_PWM1_MAX_DUTY_CYCLE	0x38
#define FAN_REG_PWM2_MAX_DUTY_CYCLE	0x39
#define FAN_REG_PWM3_MAX_DUTY_CYCLE	0x3A
#define FAN_REG_DEV_ID_REG		0x3D
    #define FAN_REG_DEV_ID_DEFAULT 	0x76
#define FAN_REG_CMPY_ID_REG		0x3E
    #define FAN_REG_CMPY_ID_DEFAULT	0x41
#define FAN_REG_REV_ID_REG		0x3F
#define FAN_REG_CFG1			0x40
#define FAN_REG_IRQ_STAT1		0x41
#define FAN_REG_IRQ_STAT2		0x42
#define FAN_REG_VID_GPIO		0x43
#define FAN_REG_2P5V_LOW_LIMIT		0x44
#define FAN_REG_2P5V_HI_LIMIT		0x45
#define FAN_REG_VCCP_LOW_LIMIT		0x46
#define FAN_REG_VCCP_HI_LIMIT		0x47
#define FAN_REG_VCC_LOW_LIMIT		0x48
#define FAN_REG_VCC_HI_LIMIT		0x49
#define FAN_REG_5V_LOW_LIMIT		0x4A
#define FAN_REG_5V_HI_LIMIT		0x4B
#define FAN_REG_12V_LOW_LIMIT		0x4C
#define FAN_REG_12V_HI_LIMIT		0x4D
#define FAN_REG_RMT1_LOW_LIMIT		0x4E
#define FAN_REG_RMT1_HI_LIMIT		0x4F
#define FAN_REG_LCL_LOW_LIMIT		0x50
#define FAN_REG_LCL_HI_LIMIT		0x51
#define FAN_REG_RMT2_LOW_LIMIT		0x52
#define FAN_REG_RMT2_HI_LIMIT		0x53
#define FAN_REG_TACH1_MIN_LOW		0x54
#define FAN_REG_TACH1_MIN_HIGH		0x55
#define FAN_REG_TACH2_MIN_LOW		0x56
#define FAN_REG_TACH2_MIN_HIGH		0x57
#define FAN_REG_TACH3_MIN_LOW		0x58
#define FAN_REG_TACH3_MIN_HIGH		0x59
#define FAN_REG_TACH4_MIN_LOW		0x5A
#define FAN_REG_TACH4_MIN_HIGH		0x5B
#define FAN_REG_PWM1_CFG		0x5C
#define FAN_REG_PWM2_CFG		0x5D
#define FAN_REG_PWM3_CFG		0x5E
#define FAN_REG_RMT1_PWM1_HZ		0x5F
#define FAN_REG_RMT1_PWM2_HZ		0x60
#define FAN_REG_RMT1_PWM3_HZ		0x61
#define FAN_REG_ENHANCED_ACOUSTICS1	0x62
#define FAN_REG_ENHANCED_ACOUSTICS2	0x63
#define FAN_REG_PWM1_MIN_DUTY_CYCLE	0x64
#define FAN_REG_PWM2_MIN_DUTY_CYCLE	0x65
#define FAN_REG_PWM3_MIN_DUTY_CYCLE	0x66
#define FAN_REG_RMT1_TEMP_MIN		0x67
#define FAN_REG_LCL_TEMP_MIN		0x68
#define FAN_REG_RMT2_TEMP_MIN		0x69
#define FAN_REG_RMT1_TEMP_LIMIT		0x6A
#define FAN_REG_LCL_TEMP_LIMIT		0x6B
#define FAN_REG_RMT2_TEMP_LIMIT		0x6C
#define FAN_REG_RMT1_TEMP_HYST		0x6D
#define FAN_REG_RMT2_TEMP_HYST		0x6E
#define FAN_REG_XNOR_TREE_TEST_EN	0x6F
#define FAN_REG_RMT1_TEMP_OFFSET	0x70
#define FAN_REG_LCL_TEMP_OFFSET		0x71
#define FAN_REG_RMT2_TEMP_OFFSET	0x72
#define FAN_REG_CFG2			0x73
#define FAN_REG_IRQ_MASK1		0x74
#define FAN_REG_IRQ_MASK2		0x75
#define FAN_REG_EXT_RES1		0x76
#define FAN_REG_EXT_RES2		0x77
#define FAN_REG_CFG3			0x78
#define FAN_REG_TIMER_STAT		0x79
#define FAN_REG_TIMER_LIMIT		0x7A
#define FAN_REG_TACH_PULSES_PER_REV	0x7B
#define FAN_REG_CFG5			0x7C
#define FAN_REG_CFG4			0x7D
#define FAN_REG_TEST1			0x7E
#define FAN_REG_TEST2			0x7F

#endif

