/******************************************************************************
 *
 * Copyright (C) 2009 Nuova/Cisco Systems, Inc.  All rights reserved
 *
 * file: prt_hw_sta_reg_test.h
 * Array's generated from prt_prt_naxislave_define.h
 ******************************************************************************/
#ifndef _PRT_HW_STA_TEST_
#define _PRT_HW_STA_TEST_
#include "prt_prt_naxislave_define.h"
/*
 * This file cannot be included in multiple c files as it has variable
 * definitions in it
 */

typedef struct _prt_sta_table_entry_ {
    unsigned int word_addr;
    unsigned int init;
} prt_sta_reg_table_entry_t;

typedef struct _prt_table_entry_ {
    char *name;
    unsigned int base_addr;
    unsigned int size;
    prt_sta_reg_table_entry_t *table;
} prt_sta_reg_table_t;

static prt_sta_reg_table_entry_t prt_sta_reg_misc [] = {
    {PRT_MISC_STA_MDIO0_OFFSET,  PRT_MISC_STA_MDIO0_DEF},
    {PRT_MISC_STA_MDIO1_OFFSET,  PRT_MISC_STA_MDIO1_DEF},
    {PRT_MISC_STA_MDIO2_OFFSET,  PRT_MISC_STA_MDIO2_DEF},
    {PRT_MISC_STA_MDIO3_OFFSET,  PRT_MISC_STA_MDIO3_DEF},
    {PRT_MISC_STA_JPC_OFFSET,  PRT_MISC_STA_JPC_DEF},
    {PRT_MISC_STA_PAD_OFFSET,  PRT_MISC_STA_PAD_DEF},
    {PRT_MISC_STA_SPARE_OFFSET,  PRT_MISC_STA_SPARE_DEF},
    {PRT_MISC_CV_STA_SERIAL_SHIFT_DONE_OUT_OFFSET,  
     PRT_MISC_CV_STA_SERIAL_SHIFT_DONE_OUT_DEF},
    {PRT_MISC_CV_STA_FUSE_DATA_OUT_OFFSET,  PRT_MISC_CV_STA_FUSE_DATA_OUT_DEF},
};

static prt_sta_reg_table_entry_t prt_sta_reg_bi[] = {
    {PRT_BI_GBE_STA_MII_OFFSET,  PRT_BI_GBE_STA_MII_DEF},
    {PRT_BI_GBE_STA_OFFSET,  PRT_BI_GBE_STA_DEF},
    {PRT_BI_STA_SPARE_OFFSET,  PRT_BI_STA_SPARE_DEF},
    {PRT_BI_DHS_MAC_STAT_OFFSET,  PRT_BI_DHS_MAC_STAT_DEF},
    {PRT_BI_STA_GBE_OFFSET,  PRT_BI_STA_GBE_DEF},
    {PRT_BI_STA_BI_SPARE_OFFSET,  PRT_BI_STA_BI_SPARE_DEF},
    {PRT_BI_STA_TX_CLASS_XOFF_OFFSET,  PRT_BI_STA_TX_CLASS_XOFF_DEF},
    {PRT_BI_STA_RX_CLASS_XOFF_OFFSET,  PRT_BI_STA_RX_CLASS_XOFF_DEF},
};

static prt_sta_reg_table_entry_t prt_sta_reg_ci[] = {
    {PRT_CI_DHS_MCAST_MEMIF_STA_OFFSET,  PRT_CI_DHS_MCAST_MEMIF_STA_DEF},
    {PRT_CI_DHS_MAC_STAT_OFFSET,  PRT_CI_DHS_MAC_STAT_DEF},
    {PRT_CI_STA_GBE_OFFSET,  PRT_CI_STA_GBE_DEF},
    {PRT_CI_STA_TX_RUNT_PKT_SIZE_OFFSET,  PRT_CI_STA_TX_RUNT_PKT_SIZE_DEF},
    {PRT_CI_STA_RX_RUNT_PKT_SIZE_OFFSET,  PRT_CI_STA_RX_RUNT_PKT_SIZE_DEF},
    {PRT_CI_STA_ECC_ADDR_OFFSET,  PRT_CI_STA_ECC_ADDR_DEF},
    {PRT_CI_STA_RX_TSTAMP_1588_OFFSET,  PRT_CI_STA_RX_TSTAMP_1588_DEF},
    {PRT_CI_STA_CI_SPARE_OFFSET,  PRT_CI_STA_CI_SPARE_DEF},
    {PRT_CI_STA_MBIST_OFFSET,  PRT_CI_STA_MBIST_DEF},
    {PRT_CI_STA_TX_CLASS_XOFF_OFFSET,  PRT_CI_STA_TX_CLASS_XOFF_DEF},
    {PRT_CI_STA_RX_CLASS_XOFF_OFFSET,  PRT_CI_STA_RX_CLASS_XOFF_DEF},
    {PRT_CI_GBE_STA_MII_OFFSET,  PRT_CI_GBE_STA_MII_DEF},
    {PRT_CI_GBE_STA_OFFSET,  PRT_CI_GBE_STA_DEF},
    {PRT_CI_STA_SPARE_OFFSET,  PRT_CI_STA_SPARE_DEF},
};

static prt_sta_reg_table_entry_t prt_sta_reg_pc[] = {
    {PRT_PC_STA_N2R0_LATCH_ADDR_OFFSET,  PRT_PC_STA_N2R0_LATCH_ADDR_DEF},
    {PRT_PC_STA_N2R1_LATCH_ADDR_OFFSET,  PRT_PC_STA_N2R1_LATCH_ADDR_DEF},
    {PRT_PC_STA_N2R2_LATCH_ADDR_OFFSET,  PRT_PC_STA_N2R2_LATCH_ADDR_DEF},
    {PRT_PC_STA_N2R3_LATCH_ADDR_OFFSET,  PRT_PC_STA_N2R3_LATCH_ADDR_DEF},
    {PRT_PC_STA_N2R4_LATCH_ADDR_OFFSET,  PRT_PC_STA_N2R4_LATCH_ADDR_DEF},
    {PRT_PC_STA_N2R5_LATCH_ADDR_OFFSET,  PRT_PC_STA_N2R5_LATCH_ADDR_DEF},
    {PRT_PC_STA_N2R6_LATCH_ADDR_OFFSET,  PRT_PC_STA_N2R6_LATCH_ADDR_DEF},
    {PRT_PC_STA_N2R7_LATCH_ADDR_OFFSET,  PRT_PC_STA_N2R7_LATCH_ADDR_DEF},
    {PRT_PC_STA_PCIE_STATUS_OFFSET,PRT_PC_STA_PCIE_STATUS_00_DEF},
    {PRT_PC_STA_PCIE_STATUS_OFFSET+1,PRT_PC_STA_PCIE_STATUS_01_DEF},
};


static prt_sta_reg_table_entry_t prt_sta_reg_rs_edma[] = {
    {PRT_RS_EDMA_INFO_OFFSET, PRT_RS_EDMA_INFO_DEF},
    {PRT_RS_EDMA_FSM_OFFSET, PRT_RS_EDMA_FSM_DEF},
    {PRT_RS_EDMA_CHANNEL_RDY0_OFFSET, PRT_RS_EDMA_CHANNEL_RDY0_DEF},
    {PRT_RS_EDMA_PENDING_READS0_OFFSET, PRT_RS_EDMA_PENDING_READS0_DEF},
    {PRT_RS_EDMA_CHANNEL_RDY1_OFFSET, PRT_RS_EDMA_CHANNEL_RDY0_DEF},
    {PRT_RS_EDMA_PENDING_READS1_OFFSET, PRT_RS_EDMA_PENDING_READS0_DEF},
};

static prt_sta_reg_table_entry_t prt_sta_reg_rs_pcie[] = {
    {PRT_RS_PCIE_STA_PCIE_CFG_OP_OFFSET, PRT_RS_PCIE_STA_PCIE_CFG_OP_DEF},
    {PRT_RS_PCIE_STA_PCIE_CFG_DATA_OFFSET, PRT_RS_PCIE_STA_PCIE_CFG_DATA_DEF},
    {PRT_RS_PCIE_STA_RST_OFFSET, PRT_RS_PCIE_STA_RST_DEF},
    {PRT_RS_PCIE_STA_MAC_OFFSET, PRT_RS_PCIE_STA_MAC_DEF},
    {PRT_RS_PCIE_STA_INT_SRC0_OFFSET, PRT_RS_PCIE_STA_INT_SRC0_DEF},
    {PRT_RS_PCIE_STA_INT_SRC1_OFFSET, PRT_RS_PCIE_STA_INT_SRC1_DEF},
    {PRT_RS_PCIE_STA_INT_SRC2_OFFSET, PRT_RS_PCIE_STA_INT_SRC2_DEF},
    {PRT_RS_PCIE_STA_INT_SRC3_OFFSET, PRT_RS_PCIE_STA_INT_SRC3_DEF},
    {PRT_RS_PCIE_STA_INT_SRC4_OFFSET, PRT_RS_PCIE_STA_INT_SRC4_DEF},
    {PRT_RS_PCIE_STA_INT_SRC5_OFFSET, PRT_RS_PCIE_STA_INT_SRC5_DEF},
    {PRT_RS_PCIE_STA_INT_SRC6_OFFSET, PRT_RS_PCIE_STA_INT_SRC6_DEF},
    {PRT_RS_PCIE_STA_INT_SRC7_OFFSET, PRT_RS_PCIE_STA_INT_SRC7_DEF},
    {PRT_RS_PCIE_STA_INT_SRC8_OFFSET, PRT_RS_PCIE_STA_INT_SRC8_DEF},
    {PRT_RS_PCIE_STA_INT_SRC9_OFFSET, PRT_RS_PCIE_STA_INT_SRC9_DEF},
    {PRT_RS_PCIE_STA_INT_SRC10_OFFSET, PRT_RS_PCIE_STA_INT_SRC10_DEF},
    {PRT_RS_PCIE_STA_INT_SRC11_OFFSET, PRT_RS_PCIE_STA_INT_SRC11_DEF},
    {PRT_RS_PCIE_STA_INT_SRC12_OFFSET, PRT_RS_PCIE_STA_INT_SRC12_DEF},
    {PRT_RS_PCIE_STA_INT_SRC13_OFFSET, PRT_RS_PCIE_STA_INT_SRC13_DEF},
    {PRT_RS_PCIE_STA_INT_SRC14_OFFSET, PRT_RS_PCIE_STA_INT_SRC14_DEF},
    {PRT_RS_PCIE_STA_INT_SRC15_OFFSET, PRT_RS_PCIE_STA_INT_SRC15_DEF},
    {PRT_RS_PCIE_STA_INT_SRC16_OFFSET, PRT_RS_PCIE_STA_INT_SRC16_DEF},
    {PRT_RS_PCIE_STA_INT_SRC17_OFFSET, PRT_RS_PCIE_STA_INT_SRC17_DEF},
    {PRT_RS_PCIE_STA_INT_SRC18_OFFSET, PRT_RS_PCIE_STA_INT_SRC18_DEF},
    {PRT_RS_PCIE_STA_INT_SRC19_OFFSET, PRT_RS_PCIE_STA_INT_SRC19_DEF},
    {PRT_RS_PCIE_STA_INT_SRC20_OFFSET, PRT_RS_PCIE_STA_INT_SRC20_DEF},
    {PRT_RS_PCIE_STA_INT_SRC21_OFFSET, PRT_RS_PCIE_STA_INT_SRC21_DEF},
    {PRT_RS_PCIE_STA_INT_SRC22_OFFSET, PRT_RS_PCIE_STA_INT_SRC22_DEF},
    {PRT_RS_PCIE_STA_INT_SRC23_OFFSET, PRT_RS_PCIE_STA_INT_SRC23_DEF},
    {PRT_RS_PCIE_STA_INT_SRC24_OFFSET, PRT_RS_PCIE_STA_INT_SRC24_DEF},
    {PRT_RS_PCIE_STA_INT_SRC25_OFFSET, PRT_RS_PCIE_STA_INT_SRC25_DEF},
    {PRT_RS_PCIE_STA_INT_SRC26_OFFSET, PRT_RS_PCIE_STA_INT_SRC26_DEF},
    {PRT_RS_PCIE_STA_INT_SRC27_OFFSET, PRT_RS_PCIE_STA_INT_SRC27_DEF},
    {PRT_RS_PCIE_STA_INT_SRC28_OFFSET, PRT_RS_PCIE_STA_INT_SRC28_DEF},
    {PRT_RS_PCIE_STA_INT_SRC29_OFFSET, PRT_RS_PCIE_STA_INT_SRC29_DEF},
    {PRT_RS_PCIE_STA_INT_SRC30_OFFSET, PRT_RS_PCIE_STA_INT_SRC30_DEF},
    {PRT_RS_PCIE_STA_INT_SRC31_OFFSET, PRT_RS_PCIE_STA_INT_SRC31_DEF},
    {PRT_RS_PCIE_STA_INT_SRC_STA_OFFSET, PRT_RS_PCIE_STA_INT_SRC_STA_DEF},
    {PRT_RS_PCIE_STA_INT_SRC_PND_OFFSET, PRT_RS_PCIE_STA_INT_SRC_PND_DEF},
    {PRT_RS_PCIE_STA_INT_VEC_STA_OFFSET, PRT_RS_PCIE_STA_INT_VEC_STA_DEF},
    {PRT_RS_PCIE_STA_INT_VEC_PND_OFFSET, PRT_RS_PCIE_STA_INT_VEC_PND_DEF},
    {PRT_RS_PCIE_STA_JTAG_DRV_OFFSET, PRT_RS_PCIE_STA_JTAG_DRV_DEF},
    {PRT_RS_PCIE_STA_I2C_DRV_OFFSET, PRT_RS_PCIE_STA_I2C_DRV_DEF},
    {PRT_RS_PCIE_STA_TAR_OFFSET, PRT_RS_PCIE_STA_TAR_DEF},
    {PRT_RS_PCIE_STA_INI_OFFSET, PRT_RS_PCIE_STA_INI_DEF},
    {PRT_RS_PCIE_STA_ERR_CNT_OP_OFFSET, PRT_RS_PCIE_STA_ERR_CNT_OP_DEF},
    {PRT_RS_PCIE_STA_ERR_CNT_DATA_OFFSET, PRT_RS_PCIE_STA_ERR_CNT_DATA_DEF},
    {PRT_RS_PCIE_STA_PHY_SERDES_OFFSET, PRT_RS_PCIE_STA_PHY_SERDES_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_CREQ_STATE_OFFSET, 
     PRT_RS_PCIE_STA_NAXI_LA_CREQ_STATE_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_CREQ_CNT_OFFSET, 
     PRT_RS_PCIE_STA_NAXI_LA_CREQ_CNT_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_CREQ_FIFO_HEAD_OFFSET, 
     PRT_RS_PCIE_STA_NAXI_LA_CREQ_FIFO_HEAD_00_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_CREQ_FIFO_HEAD_OFFSET+1,
     PRT_RS_PCIE_STA_NAXI_LA_CREQ_FIFO_HEAD_01_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_CREQ_FIFO_HEAD_OFFSET+2,
     PRT_RS_PCIE_STA_NAXI_LA_CREQ_FIFO_HEAD_02_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_DREQ_STATE_OFFSET,
     PRT_RS_PCIE_STA_NAXI_LA_DREQ_STATE_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_DREQ_CNT_OFFSET,
     PRT_RS_PCIE_STA_NAXI_LA_DREQ_CNT_00_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_DREQ_CNT_OFFSET+1,
     PRT_RS_PCIE_STA_NAXI_LA_DREQ_CNT_01_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_DREQ_FIFO_HEAD_OFFSET,
     PRT_RS_PCIE_STA_NAXI_LA_DREQ_FIFO_HEAD_00_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_DREQ_FIFO_HEAD_OFFSET+1,
     PRT_RS_PCIE_STA_NAXI_LA_DREQ_FIFO_HEAD_01_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_RREQ_STATE_OFFSET,
     PRT_RS_PCIE_STA_NAXI_LA_RREQ_STATE_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_RREQ_CNT_OFFSET,
     PRT_RS_PCIE_STA_NAXI_LA_RREQ_CNT_00_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_RREQ_CNT_OFFSET+1,
     PRT_RS_PCIE_STA_NAXI_LA_RREQ_CNT_01_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_RREQ_FIFO_HEAD_OFFSET,
     PRT_RS_PCIE_STA_NAXI_LA_RREQ_FIFO_HEAD_00_DEF},
    {PRT_RS_PCIE_STA_NAXI_LA_RREQ_FIFO_HEAD_OFFSET+1,
     PRT_RS_PCIE_STA_NAXI_LA_RREQ_FIFO_HEAD_01_DEF},
    {PRT_RS_PCIE_STA_SPARE0_OFFSET,	PRT_RS_PCIE_STA_SPARE0_DEF},
    {PRT_RS_PCIE_STA_SPARE1_OFFSET,	PRT_RS_PCIE_STA_SPARE1_DEF},
    {PRT_RS_PCIE_STA_SPARE2_OFFSET,	PRT_RS_PCIE_STA_SPARE2_DEF},
    {PRT_RS_PCIE_STA_SPARE3_OFFSET,	PRT_RS_PCIE_STA_SPARE3_DEF},
    {PRT_RS_PCIE_STA_SPARE4_OFFSET,	PRT_RS_PCIE_STA_SPARE4_DEF},
    {PRT_RS_PCIE_STA_SPARE5_OFFSET,	PRT_RS_PCIE_STA_SPARE5_DEF},
    {PRT_RS_PCIE_STA_SPARE6_OFFSET,	PRT_RS_PCIE_STA_SPARE6_DEF},
    {PRT_RS_PCIE_STA_SPARE7_OFFSET,	PRT_RS_PCIE_STA_SPARE7_DEF},
    {PRT_RS_PCIE_STA_SPARE8_OFFSET,	PRT_RS_PCIE_STA_SPARE8_DEF},
    {PRT_RS_PCIE_STA_SPARE9_OFFSET,	PRT_RS_PCIE_STA_SPARE9_DEF},
    {PRT_RS_PCIE_STA_SPARE10_OFFSET,	PRT_RS_PCIE_STA_SPARE10_DEF},
    {PRT_RS_PCIE_STA_SPARE11_OFFSET,	PRT_RS_PCIE_STA_SPARE11_DEF},
    {PRT_RS_PCIE_STA_SPARE12_OFFSET,	PRT_RS_PCIE_STA_SPARE12_DEF},
    {PRT_RS_PCIE_STA_SPARE13_OFFSET,	PRT_RS_PCIE_STA_SPARE13_DEF},
    {PRT_RS_PCIE_STA_SPARE14_OFFSET,	PRT_RS_PCIE_STA_SPARE14_DEF},
    {PRT_RS_PCIE_STA_SPARE15_OFFSET,	PRT_RS_PCIE_STA_SPARE15_DEF},
};

static prt_sta_reg_table_entry_t prt_sta_reg_hi[] = {
    {PRT_HI_STA_DROPPED_SVIF_OFFSET,	PRT_HI_STA_DROPPED_SVIF_DEF},
    {PRT_HI_STA_ERR_ADDR_OFFSET,	PRT_HI_STA_ERR_ADDR_DEF},
    {PRT_HI_STA_SERDES_OFFSET,	PRT_HI_STA_SERDES_DEF},
    {PRT_HI_STA_MBIST_OFFSET,	PRT_HI_STA_MBIST_DEF},
    {PRT_HI_DHS_STATS_OFFSET,	PRT_HI_DHS_STATS_DEF},
    {PRT_HI_STA_1588_RX_OFFSET,	PRT_HI_STA_1588_RX_DEF},
    {PRT_HI_STA_1588_TX_OFFSET,	PRT_HI_STA_1588_TX_DEF},
    {PRT_HI_STA_STAT_UPPER_OFFSET,	PRT_HI_STA_STAT_UPPER_DEF},
    {PRT_HI_STA_XOFF_OFFSET,	PRT_HI_STA_XOFF_DEF},
    {PRT_HI_STA_ARF_MBIST_OFFSET,	PRT_HI_STA_ARF_MBIST_DEF},
    {PRT_HI_HI_STA_SPARE_OFFSET,	PRT_HI_HI_STA_SPARE_DEF},
    {PRT_HI_GBE_STA_MII_OFFSET,	PRT_HI_GBE_STA_MII_DEF},
    {PRT_HI_GBE_STA_OFFSET,	PRT_HI_GBE_STA_DEF},
    {PRT_HI_STA_SPARE_OFFSET,	PRT_HI_STA_SPARE_DEF},
    {PRT_HI_DHS_MAC_STAT_OFFSET,	PRT_HI_DHS_MAC_STAT_DEF},
    {PRT_HI_STA_TX_CLASS_XOFF_OFFSET,	PRT_HI_STA_TX_CLASS_XOFF_DEF},
    {PRT_HI_STA_RX_CLASS_XOFF_OFFSET,	PRT_HI_STA_RX_CLASS_XOFF_DEF},
    {PRT_HI_STA_PCS_RX_CONFIG_DATA_OFFSET, PRT_HI_STA_PCS_RX_CONFIG_DATA_DEF},
    {PRT_HI_STA_PCS_RX_STATUS_OFFSET,	PRT_HI_STA_PCS_RX_STATUS_DEF},
    {PRT_HI_STA_PCS_FSM_STATE_OFFSET,	PRT_HI_STA_PCS_FSM_STATE_DEF},
};

static prt_sta_reg_table_entry_t prt_sta_reg_ss[] = {
    {PRT_SS_STA_FRH0_PORT0_OFFSET,	PRT_SS_STA_FRH0_PORT0_DEF},
    {PRT_SS_STA_FRH1_PORT0_OFFSET,	PRT_SS_STA_FRH1_PORT0_DEF},
    {PRT_SS_STA_FRH2_PORT0_OFFSET,	PRT_SS_STA_FRH2_PORT0_DEF},
    {PRT_SS_STA_FRH3_PORT0_OFFSET,	PRT_SS_STA_FRH3_PORT0_DEF},
    {PRT_SS_STA_FRH4_PORT0_OFFSET,	PRT_SS_STA_FRH4_PORT0_DEF},
    {PRT_SS_STA_FRH5_PORT0_OFFSET,	PRT_SS_STA_FRH5_PORT0_DEF},
    {PRT_SS_STA_FRH6_PORT0_OFFSET,	PRT_SS_STA_FRH6_PORT0_DEF},
    {PRT_SS_STA_FRH7_PORT0_OFFSET,	PRT_SS_STA_FRH7_PORT0_DEF},
    {PRT_SS_STA_MCAST0_OFFSET,	PRT_SS_STA_MCAST0_DEF},
    {PRT_SS_STA_FRH0_PORT1_OFFSET,	PRT_SS_STA_FRH0_PORT1_DEF},
    {PRT_SS_STA_FRH1_PORT1_OFFSET,	PRT_SS_STA_FRH1_PORT1_DEF},
    {PRT_SS_STA_FRH2_PORT1_OFFSET,	PRT_SS_STA_FRH2_PORT1_DEF},
    {PRT_SS_STA_FRH3_PORT1_OFFSET,	PRT_SS_STA_FRH3_PORT1_DEF},
    {PRT_SS_STA_FRH4_PORT1_OFFSET,	PRT_SS_STA_FRH4_PORT1_DEF},
    {PRT_SS_STA_FRH5_PORT1_OFFSET,	PRT_SS_STA_FRH5_PORT1_DEF},
    {PRT_SS_STA_FRH6_PORT1_OFFSET,	PRT_SS_STA_FRH6_PORT1_DEF},
    {PRT_SS_STA_FRH7_PORT1_OFFSET,	PRT_SS_STA_FRH7_PORT1_DEF},
    {PRT_SS_STA_MCAST1_OFFSET,	PRT_SS_STA_MCAST1_DEF},
    {PRT_SS_STA_FRH0_PORT2_OFFSET,	PRT_SS_STA_FRH0_PORT2_DEF},
    {PRT_SS_STA_FRH1_PORT2_OFFSET,	PRT_SS_STA_FRH1_PORT2_DEF},
    {PRT_SS_STA_FRH2_PORT2_OFFSET,	PRT_SS_STA_FRH2_PORT2_DEF},
    {PRT_SS_STA_FRH3_PORT2_OFFSET,	PRT_SS_STA_FRH3_PORT2_DEF},
    {PRT_SS_STA_FRH4_PORT2_OFFSET,	PRT_SS_STA_FRH4_PORT2_DEF},
    {PRT_SS_STA_FRH5_PORT2_OFFSET,	PRT_SS_STA_FRH5_PORT2_DEF},
    {PRT_SS_STA_FRH6_PORT2_OFFSET,	PRT_SS_STA_FRH6_PORT2_DEF},
    {PRT_SS_STA_FRH7_PORT2_OFFSET,	PRT_SS_STA_FRH7_PORT2_DEF},
    {PRT_SS_STA_MCAST2_OFFSET,	PRT_SS_STA_MCAST2_DEF},
    {PRT_SS_STA_FRH0_PORT3_OFFSET,	PRT_SS_STA_FRH0_PORT3_DEF},
    {PRT_SS_STA_FRH1_PORT3_OFFSET,	PRT_SS_STA_FRH1_PORT3_DEF},
    {PRT_SS_STA_FRH2_PORT3_OFFSET,	PRT_SS_STA_FRH2_PORT3_DEF},
    {PRT_SS_STA_FRH3_PORT3_OFFSET,	PRT_SS_STA_FRH3_PORT3_DEF},
    {PRT_SS_STA_FRH4_PORT3_OFFSET,	PRT_SS_STA_FRH4_PORT3_DEF},
    {PRT_SS_STA_FRH5_PORT3_OFFSET,	PRT_SS_STA_FRH5_PORT3_DEF},
    {PRT_SS_STA_FRH6_PORT3_OFFSET,	PRT_SS_STA_FRH6_PORT3_DEF},
    {PRT_SS_STA_FRH7_PORT3_OFFSET,	PRT_SS_STA_FRH7_PORT3_DEF},
    {PRT_SS_STA_MCAST3_OFFSET,	PRT_SS_STA_MCAST3_DEF},
    {PRT_SS_STA_FRH0_PORT4_OFFSET,	PRT_SS_STA_FRH0_PORT4_DEF},
    {PRT_SS_STA_FRH1_PORT4_OFFSET,	PRT_SS_STA_FRH1_PORT4_DEF},
    {PRT_SS_STA_FRH2_PORT4_OFFSET,	PRT_SS_STA_FRH2_PORT4_DEF},
    {PRT_SS_STA_FRH3_PORT4_OFFSET,	PRT_SS_STA_FRH3_PORT4_DEF},
    {PRT_SS_STA_FRH4_PORT4_OFFSET,	PRT_SS_STA_FRH4_PORT4_DEF},
    {PRT_SS_STA_FRH5_PORT4_OFFSET,	PRT_SS_STA_FRH5_PORT4_DEF},
    {PRT_SS_STA_FRH6_PORT4_OFFSET,	PRT_SS_STA_FRH6_PORT4_DEF},
    {PRT_SS_STA_FRH7_PORT4_OFFSET,	PRT_SS_STA_FRH7_PORT4_DEF},
    {PRT_SS_STA_MCAST4_OFFSET,	PRT_SS_STA_MCAST4_DEF},
    {PRT_SS_STA_FRH0_PORT5_OFFSET,	PRT_SS_STA_FRH0_PORT5_DEF},
    {PRT_SS_STA_FRH1_PORT5_OFFSET,	PRT_SS_STA_FRH1_PORT5_DEF},
    {PRT_SS_STA_FRH2_PORT5_OFFSET,	PRT_SS_STA_FRH2_PORT5_DEF},
    {PRT_SS_STA_FRH3_PORT5_OFFSET,	PRT_SS_STA_FRH3_PORT5_DEF},
    {PRT_SS_STA_FRH4_PORT5_OFFSET,	PRT_SS_STA_FRH4_PORT5_DEF},
    {PRT_SS_STA_FRH5_PORT5_OFFSET,	PRT_SS_STA_FRH5_PORT5_DEF},
    {PRT_SS_STA_FRH6_PORT5_OFFSET,	PRT_SS_STA_FRH6_PORT5_DEF},
    {PRT_SS_STA_FRH7_PORT5_OFFSET,	PRT_SS_STA_FRH7_PORT5_DEF},
    {PRT_SS_STA_MCAST5_OFFSET,	PRT_SS_STA_MCAST5_DEF},
    {PRT_SS_STA_FRH0_PORT6_OFFSET,	PRT_SS_STA_FRH0_PORT6_DEF},
    {PRT_SS_STA_FRH1_PORT6_OFFSET,	PRT_SS_STA_FRH1_PORT6_DEF},
    {PRT_SS_STA_FRH2_PORT6_OFFSET,	PRT_SS_STA_FRH2_PORT6_DEF},
    {PRT_SS_STA_FRH3_PORT6_OFFSET,	PRT_SS_STA_FRH3_PORT6_DEF},
    {PRT_SS_STA_FRH4_PORT6_OFFSET,	PRT_SS_STA_FRH4_PORT6_DEF},
    {PRT_SS_STA_FRH5_PORT6_OFFSET,	PRT_SS_STA_FRH5_PORT6_DEF},
    {PRT_SS_STA_FRH6_PORT6_OFFSET,	PRT_SS_STA_FRH6_PORT6_DEF},
    {PRT_SS_STA_FRH7_PORT6_OFFSET,	PRT_SS_STA_FRH7_PORT6_DEF},
    {PRT_SS_STA_MCAST6_OFFSET,	PRT_SS_STA_MCAST6_DEF},
    {PRT_SS_STA_FRH0_PORT7_OFFSET,	PRT_SS_STA_FRH0_PORT7_DEF},
    {PRT_SS_STA_FRH1_PORT7_OFFSET,	PRT_SS_STA_FRH1_PORT7_DEF},
    {PRT_SS_STA_FRH2_PORT7_OFFSET,	PRT_SS_STA_FRH2_PORT7_DEF},
    {PRT_SS_STA_FRH3_PORT7_OFFSET,	PRT_SS_STA_FRH3_PORT7_DEF},
    {PRT_SS_STA_FRH4_PORT7_OFFSET,	PRT_SS_STA_FRH4_PORT7_DEF},
    {PRT_SS_STA_FRH5_PORT7_OFFSET,	PRT_SS_STA_FRH5_PORT7_DEF},
    {PRT_SS_STA_FRH6_PORT7_OFFSET,	PRT_SS_STA_FRH6_PORT7_DEF},
    {PRT_SS_STA_FRH7_PORT7_OFFSET,	PRT_SS_STA_FRH7_PORT7_DEF},
    {PRT_SS_STA_MCAST7_OFFSET,	PRT_SS_STA_MCAST7_DEF},
    {PRT_SS_STA_FRH0_PORT8_OFFSET,	PRT_SS_STA_FRH0_PORT8_DEF},
    {PRT_SS_STA_FRH1_PORT8_OFFSET,	PRT_SS_STA_FRH1_PORT8_DEF},
    {PRT_SS_STA_FRH2_PORT8_OFFSET,	PRT_SS_STA_FRH2_PORT8_DEF},
    {PRT_SS_STA_FRH3_PORT8_OFFSET,	PRT_SS_STA_FRH3_PORT8_DEF},
    {PRT_SS_STA_FRH4_PORT8_OFFSET,	PRT_SS_STA_FRH4_PORT8_DEF},
    {PRT_SS_STA_FRH5_PORT8_OFFSET,	PRT_SS_STA_FRH5_PORT8_DEF},
    {PRT_SS_STA_FRH6_PORT8_OFFSET,	PRT_SS_STA_FRH6_PORT8_DEF},
    {PRT_SS_STA_FRH7_PORT8_OFFSET,	PRT_SS_STA_FRH7_PORT8_DEF},
    {PRT_SS_STA_MCAST8_OFFSET,	PRT_SS_STA_MCAST8_DEF},
    {PRT_SS_STA_FC_PTR_OFFSET,	PRT_SS_STA_FC_PTR_DEF},
    {PRT_SS_STA_FC_CNT_OFFSET,	PRT_SS_STA_FC_CNT_DEF},
    {PRT_SS_STA_CNTL_MEM_ECC_OFFSET,	PRT_SS_STA_CNTL_MEM_ECC_DEF},
    {PRT_SS_STA_MM0_ECC_OFFSET,	PRT_SS_STA_MM0_ECC_DEF},
    {PRT_SS_STA_MM1_ECC_OFFSET,	PRT_SS_STA_MM1_ECC_DEF},
    {PRT_SS_DHS_STATS_OFFSET,	PRT_SS_DHS_STATS_DEF},
    {PRT_SS_STA_TD_OFFSET,	PRT_SS_STA_TD_DEF},
    {PRT_SS_DHS_CNTL_MEMIF_STA_OFFSET,	PRT_SS_DHS_CNTL_MEMIF_STA_DEF},
    {PRT_SS_DHS_BULK_MEMIF_STA_OFFSET,	PRT_SS_DHS_BULK_MEMIF_STA_DEF},
    {PRT_SS_STA_MBIST_OFFSET,	PRT_SS_STA_MBIST_DEF},
};

static prt_sta_reg_table_entry_t prt_sta_reg_nr[] = {
    {PRT_NR_STA_OQ0_HI_WTRMARK_QCNTR_OFFSET,PRT_NR_STA_OQ0_HI_WTRMARK_QCNTR_DEF},
    {PRT_NR_STA_OQ0_MEM_ECC_OFFSET,	PRT_NR_STA_OQ0_MEM_ECC_DEF},
    {PRT_NR_DHS_OQ0_STATUS_OFFSET,	PRT_NR_DHS_OQ0_STATUS_DEF},
    {PRT_NR_DHS_OQ0_MEMIF_STA_OFFSET,	PRT_NR_DHS_OQ0_MEMIF_STA_DEF},
    {PRT_NR_STA_OQ1_HI_WTRMARK_QCNTR_OFFSET,PRT_NR_STA_OQ1_HI_WTRMARK_QCNTR_DEF},
    {PRT_NR_STA_OQ1_MEM_ECC_OFFSET,	PRT_NR_STA_OQ1_MEM_ECC_DEF},
    {PRT_NR_DHS_OQ1_STATUS_OFFSET,	PRT_NR_DHS_OQ1_STATUS_DEF},
    {PRT_NR_DHS_OQ1_MEMIF_STA_OFFSET,	PRT_NR_DHS_OQ1_MEMIF_STA_DEF},
    {PRT_NR_STA_OQ2_HI_WTRMARK_QCNTR_OFFSET,PRT_NR_STA_OQ2_HI_WTRMARK_QCNTR_DEF},
    {PRT_NR_STA_OQ2_MEM_ECC_OFFSET,	PRT_NR_STA_OQ2_MEM_ECC_DEF},
    {PRT_NR_DHS_OQ2_STATUS_OFFSET,	PRT_NR_DHS_OQ2_STATUS_DEF},
    {PRT_NR_DHS_OQ2_MEMIF_STA_OFFSET,	PRT_NR_DHS_OQ2_MEMIF_STA_DEF},
    {PRT_NR_STA_OQ3_HI_WTRMARK_QCNTR_OFFSET,PRT_NR_STA_OQ3_HI_WTRMARK_QCNTR_DEF},
    {PRT_NR_STA_OQ3_MEM_ECC_OFFSET,	PRT_NR_STA_OQ3_MEM_ECC_DEF},
    {PRT_NR_DHS_OQ3_STATUS_OFFSET,	PRT_NR_DHS_OQ3_STATUS_DEF},
    {PRT_NR_DHS_OQ3_MEMIF_STA_OFFSET,	PRT_NR_DHS_OQ3_MEMIF_STA_DEF},
    {PRT_NR_STA_OQ4_HI_WTRMARK_QCNTR_OFFSET,PRT_NR_STA_OQ4_HI_WTRMARK_QCNTR_DEF},
    {PRT_NR_STA_OQ4_MEM_ECC_OFFSET,	PRT_NR_STA_OQ4_MEM_ECC_DEF},
    {PRT_NR_DHS_OQ4_STATUS_OFFSET,	PRT_NR_DHS_OQ4_STATUS_DEF},
    {PRT_NR_DHS_OQ4_MEMIF_STA_OFFSET,	PRT_NR_DHS_OQ4_MEMIF_STA_DEF},
    {PRT_NR_STA_OQ5_HI_WTRMARK_QCNTR_OFFSET,PRT_NR_STA_OQ5_HI_WTRMARK_QCNTR_DEF},
    {PRT_NR_STA_OQ5_MEM_ECC_OFFSET,	PRT_NR_STA_OQ5_MEM_ECC_DEF},
    {PRT_NR_DHS_OQ5_STATUS_OFFSET,	PRT_NR_DHS_OQ5_STATUS_DEF},
    {PRT_NR_DHS_OQ5_MEMIF_STA_OFFSET,	PRT_NR_DHS_OQ5_MEMIF_STA_DEF},
    {PRT_NR_STA_MBIST_OFFSET,	PRT_NR_STA_MBIST_00_DEF},
    {PRT_NR_STA_MBIST_OFFSET+1,	PRT_NR_STA_MBIST_01_DEF},
    {PRT_NR_STA_MBIST_OFFSET+2,	PRT_NR_STA_MBIST_02_DEF},
    {PRT_NR_STA_MBIST_OFFSET+3,	PRT_NR_STA_MBIST_03_DEF},
};

static prt_sta_reg_table_entry_t prt_sta_reg_hr[] = {
    {PRT_HR_STA_OQ0_HI_WTRMARK_QCNTR_OFFSET,PRT_HR_STA_OQ0_HI_WTRMARK_QCNTR_DEF},
    {PRT_HR_STA_OQ0_MEM_ECC_OFFSET,PRT_HR_STA_OQ0_MEM_ECC_DEF},
    {PRT_HR_DHS_OQ0_STATUS_OFFSET,PRT_HR_DHS_OQ0_STATUS_DEF},
    {PRT_HR_DHS_OQ0_MEMIF_STA_OFFSET,	PRT_HR_DHS_OQ0_MEMIF_STA_DEF},
    {PRT_HR_STA_OQ1_HI_WTRMARK_QCNTR_OFFSET,PRT_HR_STA_OQ1_HI_WTRMARK_QCNTR_DEF},
    {PRT_HR_STA_OQ1_MEM_ECC_OFFSET,	PRT_HR_STA_OQ1_MEM_ECC_DEF},
    {PRT_HR_DHS_OQ1_STATUS_OFFSET,	PRT_HR_DHS_OQ1_STATUS_DEF},
    {PRT_HR_DHS_OQ1_MEMIF_STA_OFFSET,	PRT_HR_DHS_OQ1_MEMIF_STA_DEF},
    {PRT_HR_STA_OQ2_HI_WTRMARK_QCNTR_OFFSET,PRT_HR_STA_OQ2_HI_WTRMARK_QCNTR_DEF},
    {PRT_HR_STA_OQ2_MEM_ECC_OFFSET,	PRT_HR_STA_OQ2_MEM_ECC_DEF},
    {PRT_HR_DHS_OQ2_STATUS_OFFSET,	PRT_HR_DHS_OQ2_STATUS_DEF},
    {PRT_HR_DHS_OQ2_MEMIF_STA_OFFSET,	PRT_HR_DHS_OQ2_MEMIF_STA_DEF},
    {PRT_HR_STA_OQ3_HI_WTRMARK_QCNTR_OFFSET,PRT_HR_STA_OQ3_HI_WTRMARK_QCNTR_DEF},
    {PRT_HR_STA_OQ3_MEM_ECC_OFFSET,	PRT_HR_STA_OQ3_MEM_ECC_DEF},
    {PRT_HR_DHS_OQ3_STATUS_OFFSET,	PRT_HR_DHS_OQ3_STATUS_DEF},
    {PRT_HR_DHS_OQ3_MEMIF_STA_OFFSET,	PRT_HR_DHS_OQ3_MEMIF_STA_DEF},
    {PRT_HR_STA_OQ4_HI_WTRMARK_QCNTR_OFFSET,PRT_HR_STA_OQ4_HI_WTRMARK_QCNTR_DEF},
    {PRT_HR_STA_OQ4_MEM_ECC_OFFSET,	PRT_HR_STA_OQ4_MEM_ECC_DEF},
    {PRT_HR_DHS_OQ4_STATUS_OFFSET,	PRT_HR_DHS_OQ4_STATUS_DEF},
    {PRT_HR_DHS_OQ4_MEMIF_STA_OFFSET,	PRT_HR_DHS_OQ4_MEMIF_STA_DEF},
    {PRT_HR_STA_OQ5_HI_WTRMARK_QCNTR_OFFSET,PRT_HR_STA_OQ5_HI_WTRMARK_QCNTR_DEF},
    {PRT_HR_STA_OQ5_MEM_ECC_OFFSET,	PRT_HR_STA_OQ5_MEM_ECC_DEF},
    {PRT_HR_DHS_OQ5_STATUS_OFFSET,	PRT_HR_DHS_OQ5_STATUS_DEF},
    {PRT_HR_DHS_OQ5_MEMIF_STA_OFFSET,	PRT_HR_DHS_OQ5_MEMIF_STA_DEF},
    {PRT_HR_STA_MBIST_OFFSET,	PRT_HR_STA_MBIST_DEF},
};

static prt_sta_reg_table_entry_t prt_sta_reg_ni[] = {
    {PRT_NI_DHS_STATS_OFFSET,	PRT_NI_DHS_STATS_DEF},
    {PRT_NI_STA_1588_RX_OFFSET,	PRT_NI_STA_1588_RX_DEF},
    {PRT_NI_STA_1588_TX_OFFSET,	PRT_NI_STA_1588_TX_DEF},
    {PRT_NI_STA_STAT_UPPER_OFFSET,	PRT_NI_STA_STAT_UPPER_DEF},
    {PRT_NI_STA_XOFF_OFFSET,	PRT_NI_STA_XOFF_DEF},
    {PRT_NI_STA_ARF_MBIST_OFFSET,	PRT_NI_STA_ARF_MBIST_DEF},
    {PRT_NI_STA_XGMII_STATUS_OFFSET,	PRT_NI_STA_XGMII_STATUS_DEF},
    {PRT_NI_XE_DHS_STAT_OFFSET,	PRT_NI_XE_DHS_STAT_00_DEF},
    {PRT_NI_XE_DHS_STAT_OFFSET+1,	PRT_NI_XE_DHS_STAT_01_DEF},
    {PRT_NI_CT_STA_UTILIZATION_OFFSET,	PRT_NI_CT_STA_UTILIZATION_DEF},
    {PRT_NI_CT_STA_MUX_SPARE_OFFSET,	PRT_NI_CT_STA_MUX_SPARE_DEF},
    {PRT_NI_XE_STA_XG_STATS_RD_CACHE_OFFSET,PRT_NI_XE_STA_XG_STATS_RD_CACHE_DEF},
    {PRT_NI_XE_STA_XG_PAUSE_OFFSET,	PRT_NI_XE_STA_XG_PAUSE_DEF},
    {PRT_NI_XE_STA_XG_RX_RS_OFFSET,	PRT_NI_XE_STA_XG_RX_RS_DEF},
    {PRT_NI_XE_STA_XG_SPARE_OFFSET,	PRT_NI_XE_STA_XG_SPARE_DEF},
    {PRT_NI_STA_SPARE_OFFSET,	PRT_NI_STA_SPARE_DEF},
};

static prt_sta_reg_table_entry_t prt_sta_reg_nf[] = {
    {PRT_NF_STA_ECC_ERR_OFFSET,	PRT_NF_STA_ECC_ERR_DEF},
    {PRT_NF_DHS_MCAST_MEMIF_STA_OFFSET,	PRT_NF_DHS_MCAST_MEMIF_STA_DEF},
    {PRT_NF_DHS_UCAST_MEMIF_STA_OFFSET,	PRT_NF_DHS_UCAST_MEMIF_STA_DEF},
    {PRT_NF_STA_MBIST_OFFSET,	PRT_NF_STA_MBIST_DEF},
    {PRT_NF_STA_SPARE_OFFSET,	PRT_NF_STA_SPARE_DEF},
};

static prt_sta_reg_table_entry_t prt_sta_reg_hf[] = {
    {PRT_HF_STA_ERR_ADDR_OFFSET,	PRT_HF_STA_ERR_ADDR_DEF},
    {PRT_HF_STA_CNT_AC_BYTES_OFFSET,	PRT_HF_STA_CNT_AC_BYTES_00_DEF},
    {PRT_HF_STA_CNT_AC_BYTES_OFFSET+1,	PRT_HF_STA_CNT_AC_BYTES_01_DEF},
    {PRT_HF_STA_KEY_SEARCH_OFFSET,	PRT_HF_STA_KEY_SEARCH_DEF},
    {PRT_HF_STA_TOKEN_NEGATIVE_OFFSET,	PRT_HF_STA_TOKEN_NEGATIVE_00_DEF},
    {PRT_HF_STA_TOKEN_NEGATIVE_OFFSET+1,	PRT_HF_STA_TOKEN_NEGATIVE_01_DEF},
    {PRT_HF_STA_AC_ERR_ADDR_OFFSET,	PRT_HF_STA_AC_ERR_ADDR_DEF},
    {PRT_HF_STA_TCAM_TCAM_BIST_DONE_PASS_OUT_OFFSET,
     PRT_HF_STA_TCAM_TCAM_BIST_DONE_PASS_OUT_DEF},
    {PRT_HF_STA_TCAM_TCAM_BIST_DONE_FAIL_OUT_OFFSET,
     PRT_HF_STA_TCAM_TCAM_BIST_DONE_FAIL_OUT_DEF},
    {PRT_HF_STA_MBIST_OFFSET,	PRT_HF_STA_MBIST_DEF},
    {PRT_HF_STA_SPARE_OFFSET,	PRT_HF_STA_SPARE_DEF},
};

#define PRT_STAT_MISC_TBL_SZ \
        (sizeof(prt_sta_reg_misc)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_BI_TBL_SZ \
        (sizeof(prt_sta_reg_bi)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_CI_TBL_SZ \
        (sizeof(prt_sta_reg_ci)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_PC_TBL_SZ \
        (sizeof(prt_sta_reg_pc)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_HF_TBL_SZ \
        (sizeof(prt_sta_reg_hf)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_NF_TBL_SZ \
        (sizeof(prt_sta_reg_nf)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_NI_TBL_SZ \
        (sizeof(prt_sta_reg_ni)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_HR_TBL_SZ \
        (sizeof(prt_sta_reg_hr)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_NR_TBL_SZ \
        (sizeof(prt_sta_reg_nr)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_RS_EDMA_TBL_SZ \
        (sizeof(prt_sta_reg_rs_edma)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_RS_PCIE_TBL_SZ \
        (sizeof(prt_sta_reg_rs_pcie)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_HI_TBL_SZ \
        (sizeof(prt_sta_reg_hi)/sizeof(prt_sta_reg_table_entry_t))
#define PRT_STAT_SS_TBL_SZ \
        (sizeof(prt_sta_reg_ss)/sizeof(prt_sta_reg_table_entry_t))

#define HI_BASE_ADDR(x) (PRT_HI0_BASE_ADDR + \
                         (x)*(PRT_HI1_BASE_ADDR-PRT_HI0_BASE_ADDR))

#define SS_BASE_ADDR(x) (PRT_SS0_BASE_ADDR + \
                         (x)*(PRT_SS1_BASE_ADDR-PRT_SS0_BASE_ADDR))

#define NI_BASE_ADDR(x) (PRT_NI0_BASE_ADDR + \
                         (x)*(PRT_NI1_BASE_ADDR-PRT_NI0_BASE_ADDR))

#define HF_BASE_ADDR(x) (PRT_HF0_BASE_ADDR + \
                         (x)*(PRT_HF1_BASE_ADDR-PRT_HF0_BASE_ADDR))
#endif
