/********************************************************************
 *
 *      File:   mv88e3019.h
 *      Name:   Sudharshan Kadari
 *
 *      Description:
 *       Marvell Phy Register Definitions. 
 *
 *
 * Copyright (c 1985-2007 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *
 *********************************************************************/

#ifndef _MVPHY_H_
#define _MVPHY_H_

#define MVPHY_CTRL						0x00
#define MVPHY_CTRL_FLD_RESET					15
#define MVPHY_CTRL_FLD_LOOPBACK_EN				14
#define MVPHY_CTRL_FLD_SPEED					13
#define MVPHY_CTRL_FLD_AUTONEG_EN				12
#define MVPHY_CTRL_FLD_POWERDOWN				11
#define MVPHY_CTRL_FLD_ISOLATE					10
#define MVPHY_CTRL_FLD_AUTONEG_RESTART				9
#define MVPHY_CTRL_FLD_FULL_DUPLEX				8
#define MVPHY_CTRL_FLD_COLLISION_TEST				7
#define MVPHY_CTRL_FLD_UNIDIR_ENA				5

#define MVPHY_STATUS						0x01
#define MVPHY_STATUS_FLD_100BASE_T4				15
#define MVPHY_STATUS_FLD_100BASE_FDX				14
#define MVPHY_STATUS_FLD_100BASE_HDX				13
#define MVPHY_STATUS_FLD_10BASE_FDX				12
#define MVPHY_STATUS_FLD_10BASE_HDX				11
#define MVPHY_STATUS_FLD_100BASE_T2_FDX				10
#define MVPHY_STATUS_FLD_100BASE_T2_HDX				9
#define MVPHY_STATUS_FLD_EXT_STATUS				8
#define MVPHY_STATUS_FLD_UNIDIR_ABILITY				7
#define MVPHY_STATUS_FLD_MF_PREAMBLE_SUPP			6
#define MVPHY_STATUS_FLD_AUTO_NEG_COMPLETE			5
#define MVPHY_STATUS_FLD_REMOTE_FAULT				4
#define MVPHY_STATUS_FLD_AUTO_NEG_ABILITY			3
#define MVPHY_STATUS_FLD_LINK_STATUS				2
#define MVPHY_STATUS_FLD_JABBER_DETECT				1
#define MVPHY_STATUS_FLD_EXT_CAPABILITY				0

#define MVPHY_PHY_ID1_MSB					0x02
#define MVPHY_PHY_ID2_LSB					0x03

#define MVPHY_AUTONEG_ADVERTISEMENT				0x04
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_NEXT_PAGE		15
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_ACK			14
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_REMOTE_FAULT		13
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_ASYMM_PAUSE		11
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_PAUSE			10
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_100BASE_T4		9
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_100BASE_FDX		8
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_100BASE_HDX		7
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_10BASE_FDX		6
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_10BASE_HDX		5
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_SECTOR_FIELD_M		0x1F
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_SECTOR_FIELD_E		4	
#define MVPHY_AUTONEG_ADVERTISEMENT_FLD_SECTOR_FIELD_S		0	

#define MVPHY_LINK_PTNR_ABILITY					0x05
#define MVPHY_LINK_PTNR_ABILITY_FLD_NEXT_PAGE			15
#define MVPHY_LINK_PTNR_ABILITY_FLD_ACK				14
#define MVPHY_LINK_PTNR_ABILITY_FLD_REMOTE_FAULT		13
#define MVPHY_LINK_PTNR_ABILITY_FLD_LPTECH_ABLE_E		12	
#define MVPHY_LINK_PTNR_ABILITY_FLD_LPTECH_ABLE_S		5	
#define MVPHY_LINK_PTNR_ABILITY_FLD_LPTECH_ABLE_M		0x1FE
#define MVPHY_LINK_PTNR_ABILITY_FLD_SECTOR_FIELD_M		0x1F
#define MVPHY_LINK_PTNR_ABILITY_FLD_SECTOR_FIELD_E	 	4	
#define MVPHY_LINK_PTNR_ABILITY_FLD_SECTOR_FIELD_S	 	0	

#define MVPHY_AUTONEG_EXP					0x06
#define MVPHY_AUTONEG_EXP_FLD_DETECT_FAULT			4
#define MVPHY_AUTONEG_EXP_FLD_LP_NEXT_PAGE_ABLE			3
#define MVPHY_AUTONEG_EXP_FLD_LOCAL_NEXT_PAGE_ABLE		2
#define MVPHY_AUTONEG_EXP_FLD_PAGE_RECEIVED			1
#define MVPHY_AUTONEG_EXP_FLD_LP_AUTO_NEG_ABLE			0

#define MVPHY_NEXT_PAGE_TX					0x07
#define MVPHY_NEXT_PAGE_TX_FLD_NEXT_PAGE			15
#define MVPHY_NEXT_PAGE_TX_FLD_MSG_PAGE_MODE			13
#define MVPHY_NEXT_PAGE_TX_FLD_ACK2				12
#define MVPHY_NEXT_PAGE_TX_FLD_TOGGLE				11
#define MVPHY_NEXT_PAGE_TX_FLD_DATA_M				0x7FF
#define MVPHY_NEXT_PAGE_TX_FLD_DATA_E				10	
#define MVPHY_NEXT_PAGE_TX_FLD_DATA_S				0	

#define MVPHY_LINK_PTNR_NEXT_TX					0x08
#define MVPHY_LINK_PTNR_NEXT_TX_FLD_NEXT_PAGE			15
#define MVPHY_LINK_PTNR_NEXT_TX_FLD_RX_ACK			14
#define MVPHY_LINK_PTNR_NEXT_TX_FLD_RX_MSG			13
#define MVPHY_LINK_PTNR_NEXT_TX_FLD_ACK2			12
#define MVPHY_LINK_PTNR_NEXT_TX_FLD_TOGGLE			11
#define MVPHY_LINK_PTNR_NEXT_TX_FLD_DATA_M			0x7FF
#define MVPHY_LINK_PTNR_NEXT_TX_FLD_DATA_E			10	
#define MVPHY_LINK_PTNR_NEXT_TX_FLD_DATA_S			0

#define MVPHY_PHY_SPEC_CTRL					0x10
#define MVPHY_PHY_SPEC_CTRL_FLD_ENERGY_DETECT			14
#define MVPHY_PHY_SPEC_CTRL_FLD_DIS_NLP_CHECK			13
#define MVPHY_PHY_SPEC_CTRL_FLD_ENA_LP_NEXT_PAGE		12
#define MVPHY_PHY_SPEC_CTRL_FLD_DIS_LP_GEN			11
#define MVPHY_PHY_SPEC_CTRL_FLD_DIS_SCRAMBLER			9
#define MVPHY_PHY_SPEC_CTRL_FLD_DIS_FEFI			8
#define MVPHY_PHY_SPEC_CTRL_FLD_EXT_DIST_EN			7
#define MVPHY_PHY_SPEC_CTRL_FLD_MDI_CROSS_OVER_M		0x30
#define MVPHY_PHY_SPEC_CTRL_FLD_MDI_CROSS_OVER_E		5	
#define MVPHY_PHY_SPEC_CTRL_FLD_MDI_CROSS_OVER_S		4	
#define MVPHY_PHY_SPEC_CTRL_FLD_ASSERT_CRS_TX			3
#define MVPHY_PHY_SPEC_CTRL_FLD_SQE_TEST			2
#define MVPHY_PHY_SPEC_CTRL_FLD_SQE_TEST			2
#define MVPHY_PHY_SPEC_CTRL_FLD_AUTO_POL			1
#define MVPHY_PHY_SPEC_CTRL_FLD_DIS_JABBER			0

#define MVPHY_PHY_SPEC_STATUS					0x11
#define MVPHY_PHY_SPEC_STATUS_FLD_SPEED				14
#define MVPHY_PHY_SPEC_STATUS_FLD_DUPLEX			13
#define MVPHY_PHY_SPEC_STATUS_FLD_PAGE_RECEIVED			12
#define MVPHY_PHY_SPEC_STATUS_FLD_LINK				10
#define MVPHY_PHY_SPEC_STATUS_FLD_MDI_CROSS_OVER		6
#define MVPHY_PHY_SPEC_STATUS_FLD_SLEEP				4
#define MVPHY_PHY_SPEC_STATUS_FLD_POLARITY			1
#define MVPHY_PHY_SPEC_STATUS_FLD_JABBER			0

#define MVPHY_MDI0_IRQ_ENABLE					0x12
#define MVPHY_MDI0_IRQ_ENABLE_FLD_SPEED_CHANGED			14
#define MVPHY_MDI0_IRQ_ENABLE_FLD_DUPLEX_CHANGED		13
#define MVPHY_MDI0_IRQ_ENABLE_FLD_PAGE_RECIEVED			12
#define MVPHY_MDI0_IRQ_ENABLE_FLD_AUTO_NEG_COMPLETE		11
#define MVPHY_MDI0_IRQ_ENABLE_FLD_AUTO_LINK_STATUS_CHANGED	10
#define MVPHY_MDI0_IRQ_ENABLE_FLD_SYMBOL_ERROR			9
#define MVPHY_MDI0_IRQ_ENABLE_FLD_FALSE_CARRIER			8
#define MVPHY_MDI0_IRQ_ENABLE_FLD_FIFO_OVER_UNDER_FLOW		7
#define MVPHY_MDI0_IRQ_ENABLE_FLD_MDI_CROSS_OVER		6
#define MVPHY_MDI0_IRQ_ENABLE_FLD_ENERGY_DETECT			4
#define MVPHY_MDI0_IRQ_ENABLE_FLD_POLARITY_CHANGED		1
#define MVPHY_MDI0_IRQ_ENABLE_FLD_JABBER			0

#define MVPHY_MDI0_IRQ_STATUS					0x13
#define MVPHY_MDI0_IRQ_STATUS_FLD_SPEED_CHANGED			14
#define MVPHY_MDI0_IRQ_STATUS_FLD_DUPLEX_CHANGED		13
#define MVPHY_MDI0_IRQ_STATUS_FLD_PAGE_RECIEVED			12
#define MVPHY_MDI0_IRQ_STATUS_FLD_AUTO_NEG_COMPLETE		11
#define MVPHY_MDI0_IRQ_STATUS_FLD_AUTO_LINK_STATUS		10
#define MVPHY_MDI0_IRQ_STATUS_FLD_SYMBOL_ERROR			9
#define MVPHY_MDI0_IRQ_STATUS_FLD_FALSE_CARRIER			8
#define MVPHY_MDI0_IRQ_STATUS_FLD_FIFO_OVER_FLOW		7
#define MVPHY_MDI0_IRQ_STATUS_FLD_MDI_CROSS_OVER		6
#define MVPHY_MDI0_IRQ_STATUS_FLD_ENERGY_DETECT			4
#define MVPHY_MDI0_IRQ_STATUS_FLD_POLARITY_CHANGED		1
#define MVPHY_MDI0_IRQ_STATUS_FLD_JABBER			0

#define MVPHY_IRQ_PORT_SUMMARY					0x14
#define MVPHY_RX_ERR_COUNTER					0x15
#define MVPHY_LED_PARALLEL_SELECT				0x16
#define MVPHY_LED_PARALLEL_SELECT_FLD_LED1			0xF0
#define MVPHY_LED_PARALLEL_SELECT_FLD_LED1_E			7	
#define MVPHY_LED_PARALLEL_SELECT_FLD_LED1_S			4
#define MVPHY_LED_PARALLEL_SELECT_FLD_LED0			0x0F
#define MVPHY_LED_PARALLEL_SELECT_FLD_LED0_E		 	3	
#define MVPHY_LED_PARALLEL_SELECT_FLD_LED0_S			0

#define MVPHY_GLOBAL_STATUS					0x17
#define MVPHY_LED_CONTROL					0x18

#define MVPHY_LED_CONTROL_FLD_PULSE_STRETCH_M			0x7000	
#define MVPHY_LED_CONTROL_FLD_PULSE_STRETCH_E			14
#define MVPHY_LED_CONTROL_FLD_PULSE_STRETCH_S			12
#define MVPHY_LED_CONTROL_FLD_BLINK_RATE_M			0xE00
#define MVPHY_LED_CONTROL_FLD_BLINK_RATE_E			11	
#define MVPHY_LED_CONTROL_FLD_BLINK_RATE_S			9
#define MVPHY_LED_CONTROL_FLD_LED1_SPEED_SEL_M			0x38
#define MVPHY_LED_CONTROL_FLD_LED1_SPEED_SEL_E			5	
#define MVPHY_LED_CONTROL_FLD_LED1_SPEED_SEL_S			3	
#define MVPHY_LED_CONTROL_FLD_LED0_SPEED_SEL_M			7
#define MVPHY_LED_CONTROL_FLD_LED0_SPEED_SEL_E			2
#define MVPHY_LED_CONTROL_FLD_LED0_SPEED_SEL_S			0	

#define MVPHY_MANUAL_LED_OVERRIDE				0x19
#define MVPHY_MANUAL_LED_OVERRIDE_FLD_INV_LED1			13
#define MVPHY_MANUAL_LED_OVERRIDE_FLD_INV_LED0			12
#define MVPHY_MANUAL_LED_OVERRIDE_FLD_FORCE_LED1_M		0xC	
#define MVPHY_MANUAL_LED_OVERRIDE_FLD_FORCE_LED1_E		3
#define MVPHY_MANUAL_LED_OVERRIDE_FLD_FORCE_LED1_S		2
#define MVPHY_MANUAL_LED_OVERRIDE_FLD_FORCE_LED0_M		3
#define MVPHY_MANUAL_LED_OVERRIDE_FLD_FORCE_LED0_E		1
#define MVPHY_MANUAL_LED_OVERRIDE_FLD_FORCE_LED0_S		0	

#define MVPHY_VCT_N0						0x1A
#define MVPHY_VCT_N0_FLD_ENA					15
#define MVPHY_VCT_N0_FLD_TEST					13
#define MVPHY_VCT_N0_FLD_AMP_REFLECTION_M			0x1F00
#define MVPHY_VCT_N0_FLD_DIST_REFLECTION_M			0xFF

#define MVPHY_VCT_N1						0x1B
#define MVPHY_VCT_N1_FLD_TEST					13
#define MVPHY_VCT_N1_FLD_AMP_REFLECTION_M			0x1F00
#define MVPHY_VCT_N1_FLD_DIST_REFLECTION_M			0xFF


#define MVPHY_SPEC_CTRL2					0x1C
#define MVPHY_SPEC_CTRL2_FLD_MAC_INTF_MODE_M			0xC00
#define MVPHY_SPEC_CTRL2_FLD_MAC_INTF_MODE_E			11
#define MVPHY_SPEC_CTRL2_FLD_MAC_INTF_MODE_S			10
#define MVPHY_SPEC_CTRL2_FLD_NS_SEQ				7
#define MVPHY_SPEC_CTRL2_FLD_ENA_10_100_TEST			6
#define MVPHY_SPEC_CTRL2_FLD_DIS_BREAK_LINK			5
#define MVPHY_SPEC_CTRL2_FLD_ENA_LINE_LPBK			4
#define MVPHY_SPEC_CTRL2_FLD_SW_MEDIA_SEL			3
#define MVPHY_SPEC_CTRL2_FLD_TDR_WAIT_TIME			2
#define MVPHY_SPEC_CTRL2_FLD_ENA_RX_CLK				1
#define MVPHY_SPEC_CTRL2_FLD_SEL_CISA				0

#define MVPHY_TEST_MODE_SEL					0x1D
#define MVPHY_PAGE_DATA						0x1E

#endif // _MVPHY_H_
